import Head from "next/head"

export default function Head() {
  return (
    <>
      <Head>
            <title>PARADAM</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      </main>
    </>
  )
}
