import Head from 'next/head'
import axios from 'axios'
import { useEffect, useState} from 'react';
import Link from 'next/link';

export default function Home({ data }) {

  // const [data, setData] = useState([]);

  // useEffect(()=> {
  //   axios('/api').then(res => setData(res.data))
  // },[])

  // if (!data) return (<></>)


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data.map(obj => {
          return <p key={obj.name}>
            <Link href={`/detail/${obj.neme}`}><img src={obj.url} alt={obj.name} /></Link>
          </p>
        })
        }
      </main>

    </>
  )
}

// getServerSideProps, getStaicProps

// export async function getServerSideProps() {
//   const res = await axios.get(`http://localhost:3000/api`)
//   const data = res.data 

//   return { props: {data} }

// }

export async function getStaticProps() {
  const res = await axios.get(`http://localhost:3000/api`)
  const data = res.data 

  return { props: {data} }

}